name: CI
on:
  push:
    branches: [ add-devcontainer ]
  workflow_dispatch:
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/devcontainers/base:bullseye
      volumes:
        - .:/iot-hub-device-update
      options: --cpus 1 -w /iot-hub-device-update
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: troubleshoot
        run: |
          ls -al
          pwd
      - name: Setup
        run: scripts/install-deps.sh -a
      - name: Build tests
        run: scripts/build.sh --clean --build-unit-tests
      - name: Run tests
        run: |
          cd out
          ctest
